name: docs
on:
  push:
    branches:
      - main
      - develop

      
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # Add this
      id-token: write   # Add this
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}    # Add this
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme myst-parser
          pip install -e .
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
